
# System Parmeters

## Verbosity level of the logs.
logging_level: INFO

## Seed for reproducibility.
seed: 42

## Cuda device to be used. If None, CPU will be used.
device: 0

# Alignment Parameters

## Use the last checkpoint to continue training
use_last_checkpoint: False

## Threshold to be used to filter predictions.
threshold: 0.7

matcha_params:
  ## JAVA Heap Size
  max_heap: 64G
  ## Filter to generate candidates for global alignment.
  threshold: 0.5

training_params:
  epochs: 10
  batch_size: 1
  save_interval: 5

model:
  name: MlpClassifier
  params:
    layers: [128, 256, 128]

loss:
  name: BCELossWeighted
  params:
    weight: [0.01, 0.99]

optimizer:
  name: Adam
  params:
    lr: 0.001

